### ISSUE TITLE
Get Suave running

### ISSUE THREAD

**Issue by forki** [forki/suaveondocker#1]
I tried:

```
docker build -t forki/suave:0.1 .
docker run -p 8085:8083 forki/suave:0.1
```

![image](https://cloud.githubusercontent.com/assets/57396/10887562/ffa2340c-8187-11e5-83ce-2df771ca2284.png)

But I can't reach the suave server from outside.

@ademar @haf do you have some pointers for me?

**Comment by haf** [comment]
Yes, you need to bind suave to a public interface. Right now it will only respond to 127.0.0.1

**Comment by forki** [comment]
how?

**Comment by forki** [comment]
in the dockerfile?

**Comment by haf** [comment]
No, when you start suave. You make it bind either to all interfaces with the ip `0.0.0.0` and `[::]` or you make it bind to e.g. `192.168.99.101`.

**Comment by forki** [comment]
sorry I'm super noob here. can you please send a PR or give me the docker run statement (if that's the right location)?

sorry

**Comment by haf** [comment]
Sure

**Comment by haf** [comment]
I'm just setting up my machine, hence the latency.

**Comment by forki** [comment]
![image](https://cloud.githubusercontent.com/assets/57396/10902993/ff848f2e-8204-11e5-9f13-f1a5f0d03341.png)

Thx
